### ISSUE TITLE
Support more distros

### ISSUE THREAD

**Issue by Strauman** [Strauman/travis-latexbuild#14]
- [ ] MiKTeX: Strauman/latex-docker#1
- [x] LuaTeX: Strauman/latex-docker#2
- [x] XeLaTeX: Strauman/latex-docker#3

**Comment by PHPirates** [comment]
The second and third work out of the box, right? Just supply the `-lualatex` or the `-xelatex` flag to latexmk using the latexmk-flags config option.

Regarding using MikTeX, see a related question here: https://tex.stackexchange.com/questions/437553/gitlab-ci-using-miktex-docker-image

**Comment by Strauman** [comment]
True!
